#!/bin/sh

interface=$1 status=$2
if [ "$CONNECTION_ID" = "Wired connection 1" ]; then
  case $status in
    up)
	    systemctl start doh-client
      ;;
    down)
	    systemctl stop doh-client
      ;;
  esac
fi
